/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ehu.isad;

import ehu.isad.controllers.ui.*;
import ehu.isad.model.Herrialdea;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;
import java.sql.SQLException;

public class Main extends Application {
    private Parent startUI,hautatUI,errorUI,botoaUI,topUI;
    private Scene hasierakoS,hautatuS,errorS,bozkatuS,topS;
    private mainController controller;
    private ehu.isad.controllers.ui.hautatuController hautatuController;
    private errorController errorController;
    private Stage stage;
    private botoakController botoaController;
    private ehu.isad.controllers.ui.topController topController;
    public String getGreeting() {
        return "Hello world.";
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        stage = primaryStage;

        pantailakKargatu();

        stage.setTitle("Eurovision by Kerman Sanjuan");
        stage.setScene(hasierakoS);
        stage.show();
    }

    public void pantailakKargatu() throws IOException{
        //UI 1 Start page (Hasiera)
        FXMLLoader loaderStart = new FXMLLoader(getClass().getResource("/start.fxml"));
        startUI = loaderStart.load();
        controller = loaderStart.getController();
        controller.setMainApp(this);
        hasierakoS = new Scene(startUI);

        // UI 2 (Herrialdea Autatu)
        FXMLLoader loaderAukeratu = new FXMLLoader(getClass().getResource("/hautatu.fxml"));
        hautatUI = loaderAukeratu.load();
        hautatuController = loaderAukeratu.getController();
        hautatuController.setMainApp(this);
        hautatuS = new Scene(hautatUI);

        //UI Error
        FXMLLoader loaderError = new FXMLLoader(getClass().getResource("/error.fxml"));
        errorUI = loaderError.load();
        errorController = loaderError.getController();
        errorController.setMainApp(this);
        errorS = new Scene(errorUI);

        //UI Votes

        FXMLLoader loaderVotes = new FXMLLoader(getClass().getResource("/botoaEman.fxml"));
        botoaUI = loaderVotes.load();
        botoaController = loaderVotes.getController();
        botoaController.setMainApp(this);
        bozkatuS = new Scene(botoaUI);
	    //UI Top
    	FXMLLoader loaderTop = new FXMLLoader(getClass().getResource("/top.fxml"));
	    topUI = loaderTop.load();
	    topController = loaderTop.getController();
        topController.setMainApp(this);
        topS = new Scene(topUI);




    }

    public void setHautatUI(){
        stage.setTitle("Informazioaren Eguneraketa");
        stage.setScene(hautatuS);
        stage.show();

    }
    public void setErrorUI() throws SQLException {
        Herrialdea herrialdea = hautatuController.bidali();
        errorController.aldatu(herrialdea);
        stage.setTitle(herrialdea.toString()+"-ren Inguruneko informazioa");
        stage.setScene(errorS);
        stage.show();

    }
    public void setBotoakUI() throws SQLException {
        //Lines to add
        Herrialdea herrialdea = hautatuController.bidali();
        botoaController.hasieratu(herrialdea);

        //Scene holder.
        stage.setTitle("Bozkaketa panela");
        stage.setScene(bozkatuS);
        stage.show();
    }
    public void setTopUI() throws SQLException{
        topController.set();
        stage.setTitle("TOP eurobisioa");
        stage.setScene(topS);
        stage.show();

    }

}

